import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { resolveCreateAssetPath } from "../asset-path.js";
import { PAGINATION_SCHEMA, paged } from "../pagination.js";
import { actions as epicActions, schema as epicSchema } from "./epic/blueprint.generated.js";

export const blueprintTool: ToolDef = categoryTool(
  "blueprint",
  "Blueprint reading, authoring, and compilation, including AnimGraph/EventGraph node scripting: add_node, connect_pins, search_node_types, plus variables, functions, graphs, components, interfaces, and event dispatchers.",
  {
    read:              bp("read", "Read BP structure incl. SCS components AND inherited native components from the CDO (CharacterMesh0, CharMoveComp, etc.). assetPath also accepts a World/umap path such as /Game/Maps/SomeLevel, which resolves to that map's level script Blueprint at PersistentLevel.<MapName>; the result reports blueprintPath and isLevelScript so you can see what answered (#942). Params: assetPath, includeComponentProperties? (dump UPROPERTY name/type/value per component template; off by default) (#353/#370)", "read_blueprint", (p) => ({ path: p.assetPath, includeComponentProperties: p.includeComponentProperties })),
    list_variables:    bp("read", paged("List variables with name, type, guid, category, tooltip, exposeOnSpawn, blueprintReadOnly, private, and editFlag ('EditAnywhere'|'EditDefaultsOnly'|'EditInstanceOnly'|'none'). instanceEditable is true only for EditAnywhere and EditInstanceOnly - EditDefaultsOnly is class-defaults-only and reports false (#744). private is reported separately because it is a Blueprint-graph access flag, not a details-panel one. Pass includeValues to add each variable's RESOLVED default from the generated-class CDO (value, valueText, cppType, declaringClass, inherited) plus one packageDirty/persisted verdict for the listing; off by default so the declaration list stays small (#902). Params: assetPath, includeValues?"), "list_blueprint_variables", (p) => ({ path: p.assetPath, includeValues: p.includeValues, cursor: p.cursor, limit: p.limit })),
    list_functions:    bp("read", paged("List the whole graph surface of a Blueprint, matching what list_graphs reports. Every entry carries kind ('function' own declaration | 'override' of a parent function | 'interface' implementation | 'event_graph' | 'event' entry point on an event graph | 'macro' | 'delegate_signature' | 'subgraph' collapsed graph | 'inherited'), source ('own'|'parent'|'interface'), graphName, and declaringClass/declaringClassPath where one applies. name and nodeCount are unchanged; nodeCount is 0 for entries that are not graphs. Params: assetPath, includeInherited? (append overridable parent/interface functions this Blueprint has not implemented, default false) (#809)"), "list_blueprint_functions", (p) => ({ path: p.assetPath, includeInherited: p.includeInherited, cursor: p.cursor, limit: p.limit })),
    read_graph:        bp("read", "Read graph nodes. Supports pagination, file dumps, and title/class node filters. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942). With includeDefaults, literal FText pin values are returned inline (defaultValue falls back to the pin's text literal, plus an explicit defaultTextValue) and object-ref pins report defaultObject (#743). Params: assetPath, graphName, offset?, limit?, includePins?, includeDefaults?, includeComments?, dumpToFile?, outputPath?, titleFilter?, classFilter? (#560)", "read_blueprint_graph", (p) => ({ path: p.assetPath, graphName: p.graphName, offset: p.offset, limit: p.limit, includePins: p.includePins, includeDefaults: p.includeDefaults, includeComments: p.includeComments, dumpToFile: p.dumpToFile, outputPath: p.outputPath, titleFilter: p.titleFilter, classFilter: p.classFilter })),
    read_graph_summary: bp("read", "Lightweight graph summary (~10KB). Returns nodes plus wires split across two arrays, execEdges and dataEdges, not a single combined edges array. Filterable node list. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942). Params: assetPath, graphName?, titleFilter?, classFilter? (#560)", "read_blueprint_graph_summary", (p) => ({ path: p.assetPath, graphName: p.graphName, titleFilter: p.titleFilter, classFilter: p.classFilter })),
    get_execution_flow: bp("read", "Trace exec pins from an entry point. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942). Params: assetPath, graphName?, entryPoint?", "get_blueprint_execution_flow", (p) => ({ path: p.assetPath, graphName: p.graphName, entryPoint: p.entryPoint })),
    get_dependencies:   bp("read", "Forward (classes/functions/assets) or reverse (referencers) deps. Params: assetPath, reverse?", "get_blueprint_dependencies", (p) => ({ path: p.assetPath, reverse: p.reverse })),
    diff:               bp("read", "Semantic structural diff between two Blueprints (binary uassets are unreviewable in git). Compares parent class, variables (type/default), functions/macros, components, and per-graph node + connection deltas keyed on stable node GUIDs so edits are matched rather than shown as remove+add. Returns a structured delta plus a human summary and changeCount. Params: assetPath (base/A), otherPath (compare/B). Revision-based diffing (fromRevision/toRevision via source control) is a staged follow-up.", "diff_blueprint", (p) => ({ assetPath: p.assetPath, otherPath: p.otherPath, fromRevision: p.fromRevision, toRevision: p.toRevision })),
    create:            bp("mutate", "Create Blueprint. assetPath is the full destination, e.g. /Game/Blueprints/BP_Example; a name plus packagePath pair is accepted as the same thing. A .uasset suffix, an object suffix, and backslashes are normalized away rather than reaching the editor as an invalid asset name. Params: assetPath, name?, packagePath?, parentClass?", "create_blueprint", (p) => ({ path: resolveCreateAssetPath(p), parentClass: p.parentClass })),
    add_variable:      bp("mutate", "Add variable. varType accepts bool/int/float/string/name/text/byte/vector/rotator/transform/gameplaytag, object:/Script/Module.Class, struct:/Game/Path/To/Struct, or a full class/struct path. Unrecognized types are rejected rather than silently defaulting. Params: assetPath, name, varType (alias: type), onConflict? (skip|error, default skip) (#745)", "add_variable", (p) => ({ path: p.assetPath, name: p.name, type: p.varType ?? p.type, onConflict: p.onConflict })),
    set_variable_properties: bp("mutate", "Edit variable properties. Note: replication is set with networking(set_property_replicated), and blueprintReadOnly is not writable here - list_variables reports it. Params: assetPath, name, editFlag? (EditAnywhere|EditDefaultsOnly|EditInstanceOnly|none - the exact value list_variables reports, and the only form that round-trips every state), instanceEditable? (two-state shorthand; mutually exclusive with editFlag), private?, category?, tooltip?, exposeOnSpawn?", "set_variable_properties", (p) => ({ path: p.assetPath, name: p.name, instanceEditable: p.instanceEditable, editFlag: p.editFlag, private: p.private, category: p.category, tooltip: p.tooltip, exposeOnSpawn: p.exposeOnSpawn })),
    create_function:   bp("mutate", "Create function. Params: assetPath, functionName", "create_function", (p) => ({ path: p.assetPath, functionName: p.functionName })),
    delete_function:   bp("mutate", "Delete function. Params: assetPath, functionName", "delete_function", (p) => ({ path: p.assetPath, functionName: p.functionName })),
    rename_function:   bp("mutate", "Rename function. Params: assetPath, oldName, newName", "rename_function", (p) => ({ path: p.assetPath, oldName: p.oldName, newName: p.newName })),
    add_node:          bp("mutate", "Add graph node. For a CallFunction node bound to a custom C++ UFUNCTION, pass nodeParams {functionName, className (or targetClass) = /Script/Module.Class}; the function also resolves against the BP's own component classes and an unambiguous loaded BlueprintCallable function, producing a bound node with pins instead of a stub (#546). nodeClass='CallParent' places a 'Parent: <Function>' call bound to the parent implementation (functionName resolves against ParentClass) so an override graph can chain to the base (#688). Params: assetPath, graphName?, nodeClass, nodeParams?", "add_node", (p) => ({ path: p.assetPath, graphName: p.graphName ?? "EventGraph", nodeClass: p.nodeClass, nodeParams: p.nodeParams })),
    delete_node:       bp("mutate", "Delete a node, addressed by nodeId (the GUID get_connections and find_nodes report) or by nodeName. Prefer the GUID: a title is ambiguous the moment a graph holds two nodes with the same one, and a GUID survives a recompile. Params: assetPath, graphName?, nodeId OR nodeName (#996)", "delete_node", (p) => ({ path: p.assetPath, graphName: p.graphName, nodeId: p.nodeId, nodeName: p.nodeName })),
    set_node_property: bp("mutate", "Set node pin default or struct property. Params: assetPath, graphName, nodeName, propertyName, value", "set_node_property", (p) => ({ path: p.assetPath, graphName: p.graphName, nodeName: p.nodeName, propertyName: p.propertyName, value: p.value })),
    connect_pins:      bp("mutate", "Wire nodes. Address each end by sourceNodeId/targetNodeId (the GUIDs get_connections and find_nodes report) or by sourceNode/targetNode title. Prefer the GUIDs: a title cannot pick one of five identically titled math nodes apart, which is what makes re-targeting wiring by title unsafe. Params: assetPath, sourceNodeId OR sourceNode, sourcePin, targetNodeId OR targetNode, targetPin, graphName?, breakExistingSource?, breakExistingTarget? (#996)", "connect_pins"),
    add_component:     bp("mutate", "Add BP component. componentClass accepts short names (e.g. 'ChildActorComponent') or full paths. For a ChildActorComponent, pass childActorClass to set its ChildActorClass in the same call (a Blueprint path with or without _C, or a C++ class) (#526). Params: assetPath, componentClass, componentName?, parentComponent? (SCS parent for hierarchy - #115), childActorClass?", "add_component", (p) => ({ path: p.assetPath, componentClass: p.componentClass, componentName: p.componentName ?? p.componentClass, parentComponent: p.parentComponent, childActorClass: p.childActorClass })),
    remove_component:  bp("mutate", "Remove SCS component. Params: assetPath, componentName", "remove_component", (p) => ({ path: p.assetPath, componentName: p.componentName })),
    set_component_property: bp("mutate", "Set property on SCS or inherited component. Inherited components go through the child BP's InheritableComponentHandler override template so the parent stays untouched. Pass value=null to clear a TObjectPtr/SoftObject/WeakObject/UClass/Interface reference (e.g. clear AnimClass on CharacterMesh0) (#420). Params: assetPath, componentName, propertyName, value", "set_blueprint_component_property", (p) => ({ path: p.assetPath, componentName: p.componentName, propertyName: p.propertyName, value: p.value })),
    set_component_override_materials: bp("mutate", "Write OverrideMaterials on a mesh-component template (StaticMeshComponent / SkeletalMeshComponent / any UMeshComponent). Pass materialPaths as a string[] of material asset paths (empty array clears). Avoids any TArray<UObject*> coercion on the generic set_component_property path (#442). Params: assetPath, componentName, materialPaths", "set_component_override_materials", (p) => ({ assetPath: p.assetPath, componentName: p.componentName, materialPaths: p.materialPaths })),
    add_timeline_track: bp("mutate", "Add a track to a Blueprint timeline. Creates the UTimelineTemplate if missing, builds the matching curve asset (float/vector/color/event), applies keyframes, bumps TimelineLength to cover the last key, then recompiles so K2Node_Timeline regenerates its output pins. Params: assetPath, timelineName, trackName, trackType ('float'|'vector'|'color'|'event'), keyframes ([{time, value}]). value is a number for float/event, {x,y,z} for vector, {r,g,b,a} for color (#457)", "add_timeline_track", (p) => ({ assetPath: p.assetPath, timelineName: p.timelineName, trackName: p.trackName, trackType: p.trackType, keyframes: p.keyframes })),
    set_capsule_size: bp("mutate", "Call UCapsuleComponent::SetCapsuleSize on a CapsuleComponent template (CharacterMovement-friendly path; raw property writes leave the visualizer stale). Pass either or both of halfHeight/radius. Returns the new + previous values. Params: assetPath, componentName, halfHeight?, radius? (#419)", "set_capsule_size", (p) => ({ path: p.assetPath, componentName: p.componentName, halfHeight: p.halfHeight, radius: p.radius })),
    get_component_property: bp("read", "Read a single property value from an SCS or inherited component template. Returns the ICH override value for child BPs if one exists. Params: assetPath, componentName, propertyName", "get_blueprint_component_property", (p) => ({ path: p.assetPath, componentName: p.componentName, propertyName: p.propertyName })),
    set_class_default: bp("mutate", "Set UPROPERTY on Blueprint CDO. Pass value=null to clear an object/class/interface reference (#420). Params: assetPath, propertyName, value", "set_class_default", (p) => ({ path: p.assetPath, propertyName: p.propertyName, value: p.value })),
    delete_variable:   bp("mutate", "Delete a member variable. Params: assetPath, name", "delete_variable", (p) => ({ path: p.assetPath, name: p.name })),
    add_function_parameter: bp("mutate", "Add input or output parameter to a function. Params: assetPath, functionName, parameterName, parameterType?, isOutput?", "add_function_parameter", (p) => ({ path: p.assetPath, functionName: p.functionName, parameterName: p.parameterName, parameterType: p.parameterType, isOutput: p.isOutput })),
    set_variable_default: bp("mutate", "Set default value on a BP variable. Params: assetPath, name, value", "set_variable_default", (p) => ({ path: p.assetPath, name: p.name, value: p.value })),
    get_variable_default: bp("read", "Read the RESOLVED default of a BP variable off the generated-class CDO, which is what a write-compile-readback loop has to compare against (list_variables alone only proves the variable exists). Returns value (typed JSON), valueText (UE export text), cppType, declaringClass/declaringClassPath and inherited. It also states whether that value is on DISK: packageDirty is the package's own unsaved-changes flag and persisted is its inverse, so a value written into the CDO but never saved reports persisted=false with a persistenceNote instead of reading back as if it had landed (#931). authoredDefault/matchesAuthoredDefault appear when the variable carries a non-empty authored default string that the next recompile could apply. Params: assetPath, name (#902)", "get_blueprint_variable_default", (p) => ({ path: p.assetPath, name: p.name })),
    compile:           bp("mutate", "Compile Blueprint. Params: assetPath", "compile_blueprint", (p) => ({ path: p.assetPath })),
    list_node_types:   bp("read", paged("List node types. Params: category?, includeFunctions?"), "list_node_types"),
    get_connections: bp("read", paged("Read a Blueprint graph's edges, addressed by node GUID. read_graph reports each pin as connected true or false and never says to what, and read_graph_summary carries exec edges but no data edges, so there was no native way to answer \"what feeds this pin\" - which is what verifying or re-targeting wiring needs. Each edge carries fromNodeId/fromPin and toNodeId/toPin plus both node titles and classes, and a data edge also carries its pin category. Nodes are named by GUID because a title is exactly what is ambiguous when a graph holds five \"float * float\" nodes, and a GUID survives a recompile. Every edge is reported once, from its output side, which is the direction it actually has. Omit graphName to read every graph the Blueprint owns. Pass dumpToFile=true to write the complete edge set to JSON instead of returning a large inline result. Params: assetPath, graphName? OR graphSelector?, kind? (exec|data|all, default all), includeNestedGraphs? (default true) (#996)"), "get_blueprint_connections", (p) => ({ assetPath: p.assetPath, graphName: p.graphName, graphSelector: p.graphSelector, kind: p.kind, includeNestedGraphs: p.includeNestedGraphs, limit: p.limit, cursor: p.cursor, offset: p.offset, dumpToFile: p.dumpToFile, outputPath: p.outputPath })),
    find_nodes: bp("read", paged("Find nodes anywhere in ONE Blueprint, across every graph it owns including collapsed and nested ones. Narrow by `titles` (case-insensitive substrings matched against the node title), `nodeClasses` (exact class names such as K2Node_VariableGet), or `variableName` with an optional `variableAccess` of get|set|any - which is how you find every read and write of a member, the variable analogue of search_call_sites. The three are alternatives rather than a conjunction, so one pass answers \"every get of bIsAiming, plus anything titled Sprint\". read_graph and epic_find_nodes take one named graph at a time and do not descend into a collapsed subgraph; this walks them all. Each hit carries the graph selector list_graphs reports, the node title, class and GUID, which filter matched it, and for a variable node the member name, whether it is a get or a set, and its parent class. authoredOnly (default true) leaves out transient compiler graphs. A call naming none of the three filters is refused rather than dumping the Blueprint. Params: assetPath (a World path resolves to its level script), titles?, nodeClasses?, variableName?, variableAccess?, includeNestedGraphs? (default true), authoredOnly? (default true) (#998/#1015)"), "search_blueprint_nodes", (p) => ({ assetPath: p.assetPath, titles: p.titles, nodeClasses: p.nodeClasses, variableName: p.variableName, variableAccess: p.variableAccess, includeNestedGraphs: p.includeNestedGraphs, authoredOnly: p.authoredOnly, limit: p.limit, cursor: p.cursor, offset: p.offset })),
    search_call_sites: bp("read", paged("Find authored call-site NODES for named functions across a whole directory in ONE call, including nested and collapsed graphs. Replaces the enumerate-every-Blueprint / read-every-graph sweep that overwhelms the bridge on a large project. Narrowing is done by the Asset Registry BEFORE any package is loaded: candidates come from a recursive Blueprint filter over `directory`, then every candidate whose package does not depend on a package declaring one of `functionNames` is ruled out unloaded. That step is reported (stats.narrowedByRegistry, stats.blueprintsSkippedByRegistry) and can be turned off with narrowByRegistry=false; it is also skipped automatically when a requested name has no resolvable declaring class, so a filter never silently drops a hit. Each hit carries assetPath, packageName, graphName + graphSelector (the same selector list_graphs reports, so it is unambiguous for duplicate nested graph names) + graphObjectPath, nodeId, nodeTitle, memberName, resolvedFunction (absent with unresolvedTarget=true when the function is gone, which is itself an audit finding), declaringClass/declaringClassPath, parentCall, and pinDefaults for unlinked input pins. Pass includeNeighbours for the immediate execution and data neighbours of each call. Level script Blueprints are NOT registry assets (they live inside their map package), so they are excluded unless you pass includeLevelScripts, which sweeps the World assets under the directory and costs a full map load each. Bounded and paginated: limit (default 200, max 1000) + offset, maxBlueprints (default 2000) caps package loads, and dumpToFile writes the whole result set to a JSON file the way read_graph does. Params: functionNames[], className?, directory? (default /Game), includeNestedGraphs? (default true), includeLevelScripts?, includeNeighbours?, narrowByRegistry?, offset?, limit?, maxBlueprints?, dumpToFile?, outputPath? (#945)"), "search_blueprint_call_sites", (p) => ({ functionNames: p.functionNames, className: p.className, directory: p.directory, includeNestedGraphs: p.includeNestedGraphs, includeLevelScripts: p.includeLevelScripts, includeNeighbours: p.includeNeighbours, narrowByRegistry: p.narrowByRegistry, offset: p.offset, cursor: p.cursor, limit: p.limit, maxBlueprints: p.maxBlueprints, dumpToFile: p.dumpToFile, outputPath: p.outputPath })),
    search_node_types: bp("read", paged("Search placeable nodes across every loaded Blueprint function library (KismetMathLibrary, GameplayStatics, custom libraries) plus UEdGraphNode classes. Matches the C++ name, the palette label from DisplayName metadata, and Keywords metadata, ignoring case/spaces/underscores, so 'is point in box' finds IsPointInBox and 'vector length' finds VSize. Results are ranked and each carries an addNode block (nodeClass + nodeParams incl. targetClass) that add_node accepts verbatim. Params: query, limit? (default 50), className? (narrow to one owning class), includeGraphNodes? (#808)"), "search_node_types"),
    create_interface:  bp("mutate", "Create BP Interface. Params: assetPath", "create_blueprint_interface", (p) => ({ path: p.assetPath })),
    add_interface:     bp("mutate", "Implement interface. Params: blueprintPath, interfacePath", "add_blueprint_interface"),
    override_function: bp("mutate", "Override an inherited interface implementation (inherited via the parent class) or an overridable parent virtual function, with the matching signature so it actually binds as the override (create_function makes a blank, non-binding graph). Returns kind ('function' with a graphName, or 'event' with a nodeId in EventGraph). Event-shaped functions become override events unless preferFunction=true. This is the path for BehaviorTree TASK Blueprint entry points: ReceiveExecuteAI and ReceiveAbortAI on a UBTTask_BlueprintBase child come back as kind='event' in EventGraph, and their FinishExecute / FinishAbort terminators are placed with add_node nodeClass='CallFunction', className='/Script/AIModule.BTTask_BlueprintBase' (#886). Pass interfacePath to also implement the interface first if it is not present. Then wire the body with add_node (use nodeClass='CallParent' to chain to the base implementation). An animation layer override in a child Anim BP is created as an AnimationGraph on the animation schema, mirrored from the graph that declared the layer, so it actually binds instead of compiling to an inert K2 function graph; the result reports graphClass, schemaClass and animationGraph (#894). Params: assetPath, functionName, source? ('auto'|'interface'|'parent', advisory), preferFunction?, interfacePath? (#688)", "override_function", (p) => ({ path: p.assetPath, functionName: p.functionName, source: p.source, preferFunction: p.preferFunction, interfacePath: p.interfacePath })),
    list_overridable_functions: bp("read", "List functions this Blueprint can override: inherited interface implementations and overridable parent virtuals. Each entry has name, source ('interface'|'parent'), declaringClass, canBeEvent. Params: assetPath (#688)", "list_overridable_functions", (p) => ({ path: p.assetPath })),
    list_graphs:       bp("read", "List all graphs in a blueprint. Returns selector/objectPath plus duplicateIndex/duplicateCount; pass selector back as graphName for unambiguous nested graph edits. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942). Params: assetPath", "list_blueprint_graphs", (p) => ({ path: p.assetPath })),
    resolve_graph:     bp("read", "Resolve a Blueprint graph name to selectors accepted by read_graph/add_node/connect_pins and other graph actions. assetPath accepts a World/umap path, resolved to that map's level script Blueprint (#942). Duplicate nested AnimBP names such as Locomotion return every match with selectors like Locomotion[3], object paths, and ambiguity metadata. Params: assetPath, graphName", "resolve_blueprint_graph", (p) => ({ path: p.assetPath, graphName: p.graphName })),
    add_event_dispatcher: bp("mutate", "Add event dispatcher (multicast delegate variable + signature graph + UFunction). Without parameters, broadcasters fire void(). With parameters, the signature graph gets typed user pins so K2Node_CallDelegate compiles cleanly (#276). Params: blueprintPath, name, parameters?: [{name, type}] where type is bool/int/float/string/name/text/vector/rotator/transform/object:/Script/Module.Class/struct:/Script/Module.Struct", "add_event_dispatcher"),
    duplicate:         bp("mutate", "Duplicate blueprint asset. Params: sourcePath, destinationPath", "duplicate_blueprint"),
    add_local_variable: bp("mutate", "Add function-scope local variable. Params: assetPath, functionName, name, varType? (alias: type, default bool)", "add_local_variable", (p) => ({ assetPath: p.assetPath, functionName: p.functionName, name: p.name, varType: p.varType ?? p.type })),
    list_local_variables: bp("read", "List local variables in a function. Params: assetPath, functionName", "list_local_variables"),
    validate:          bp("read", "Validate blueprint without saving (compile + collect diagnostics). Params: assetPath", "validate_blueprint"),
    read_component_properties: bp("read", "Dump ALL UPROPERTYs on a BP component template incl. array contents (#105). Params: assetPath, componentName", "read_component_properties", (p) => ({ path: p.assetPath, componentName: p.componentName })),
    get_component_collision: bp("read", "Read a component's EFFECTIVE collision: enabled mode, object type, profile name, and the resolved Block/Overlap/Ignore per channel. read_component_properties cannot answer this - it exports BodyInstance as text, and that text carries only CollisionProfileName plus the responses that DIFFER from the profile, so a response INHERITED from the profile (the Pawn profile blocking Camera) is invisible in it. Each channel reports response (what GetCollisionResponseToChannel actually returns), profileResponse, and overridesProfile, so you can see whether an answer came from the profile or from the component. assetPath takes a Blueprint path OR a native class (/Script/MyGame.MyCharacter or 'MyCharacter'), which is how you verify a C++ constructor's SetCollisionResponseToChannel really landed in the CDO after a rebuild. Project trace and object channels appear under their configured names with enumName alongside. channel narrows it to one; includeAllChannels adds the unused GameTraceChannel slots. Params: assetPath, componentName, channel?, includeAllChannels? (#925)", "get_component_collision", (p) => ({ assetPath: p.assetPath, componentName: p.componentName, channel: p.channel, includeAllChannels: p.includeAllChannels })),
    read_node_property: bp("read", "Read a node pin default OR a reflected node property for verification (#102). Params: assetPath, graphName?, nodeName, propertyName", "read_node_property", (p) => ({ path: p.assetPath, graphName: p.graphName, nodeName: p.nodeName, propertyName: p.propertyName })),
    reparent_component: bp("mutate", "Reparent an SCS component under a new parent, recompile and save (#115). Refuses before touching anything when the Blueprint's .uasset is read-only on disk (not checked out) or on a protected mount, and reports saved plus saveError when the write did not reach disk (#932). Params: assetPath, componentName, newParent", "reparent_component", (p) => ({ path: p.assetPath, componentName: p.componentName, newParent: p.newParent })),
    reparent: bp("mutate", "Change a Blueprint's ParentClass, recompile and save (#138). The save is part of the operation, so writability is checked FIRST: a read-only .uasset (never checked out of source control) or a protected mount returns reason='package_not_writable' naming the file, with nothing reparented, instead of taking the editor down with a fatal save error (#932). A write that still did not reach disk comes back with saved=false and saveError. Params: assetPath, parentClass (short name or full path).", "reparent_blueprint", (p) => ({ path: p.assetPath, parentClass: p.parentClass })),
    flush_ich: bp("mutate", "Flush orphaned InheritableComponentHandler override records (invalid component-override entries invisible to read/remove_component). Recompiles + saves. Params: assetPath. Returns recordsBefore/After/Removed (#580)", "flush_inheritable_component_handler", (p) => ({ path: p.assetPath })),
    flush_component_templates: {
      ...bp("mutate", "Flush orphaned UBlueprint::ComponentTemplates left by deleted Add Component nodes using Unreal's native maintenance routine. Live Add Component templates are preserved. Recompiles + saves only when changed. Params: assetPath. Returns recordsBefore/After/Removed and removed template identities.", "flush_blueprint_component_templates", (p) => ({ path: p.assetPath })),
      timeoutMs: 120_000,
    },
    set_actor_tick_settings: bp("mutate", "Set actor CDO tick settings (#116). Params: assetPath, bCanEverTick?, bStartWithTickEnabled?, TickInterval?", "set_actor_tick_settings", (p) => ({ path: p.assetPath, bCanEverTick: p.bCanEverTick, bStartWithTickEnabled: p.bStartWithTickEnabled, TickInterval: p.TickInterval })),
    export_nodes_t3d:  bp("read", "Export graph nodes as T3D text (Ctrl+C equivalent) for bulk round-trip (#130). Params: assetPath, graphName?, nodeIds? (omit = whole graph)", "export_nodes_t3d", (p) => ({ path: p.assetPath, graphName: p.graphName ?? "EventGraph", nodeIds: p.nodeIds })),
    import_nodes_t3d:  bp("mutate", "Paste a T3D node blob into a graph (Ctrl+V equivalent) for bulk authoring (#130). Params: assetPath, graphName?, t3d, posX?, posY?", "import_nodes_t3d", (p) => ({ path: p.assetPath, graphName: p.graphName ?? "EventGraph", t3d: p.t3d, posX: p.posX, posY: p.posY })),
    set_cdo_property:  bp("mutate", "Set UPROPERTY on any C++ class CDO (not just Blueprints). Params: className, propertyName, value (#182/#183)", "set_cdo_property"),
    get_cdo_properties: bp("read", "Read UPROPERTY values from any C++ class CDO. Params: className, propertyNames? (#183)", "get_cdo_properties"),
    run_construction_script: bp("mutate", "Spawn temp actor, run construction script, return generated components and transforms. Params: assetPath, location? (#195)", "run_construction_script", (p) => ({ path: p.assetPath, location: p.location })),
    compile_all: bp("mutate", "Batch compile + save Blueprints. Params: assetPaths[], save? (default true). Returns per-path status (compiled/failed/not_found) (#284)", "compile_blueprints", (p) => ({ assetPaths: p.assetPaths, save: p.save })),
    author: {
      kind: "handler",
      effect: "mutate",
      description: "Author a whole Blueprint in one call: optionally create it (parentClass), then add components, variables and function stubs, then compile - one agent-facing action instead of a dozen add_* round-trips. Params: assetPath, parentClass? (create/ensure the BP if given), components? [{componentClass, componentName?, parentComponent?, childActorClass?}], variables? [{name, varType}], functions? [{functionName}], compile? (default true). Returns per-step results + created flag. (#607)",
      handler: async (ctx, p) => {
        const assetPath = p.assetPath as string;
        if (!assetPath) throw new Error("Missing 'assetPath'");
        const steps: Array<{ step: string; target: string; ok: boolean; result?: unknown; error?: string }> = [];
        const run = async (step: string, target: string, method: string, params: Record<string, unknown>) => {
          try { const result = await ctx.bridge.call(method, params); steps.push({ step, target, ok: true, result }); }
          catch (e) { steps.push({ step, target, ok: false, error: e instanceof Error ? e.message : String(e) }); }
        };
        let created = false;
        if (p.parentClass) {
          try {
            const r = await ctx.bridge.call("create_blueprint", { path: assetPath, parentClass: p.parentClass }) as Record<string, unknown>;
            created = r?.created !== false;
            steps.push({ step: "create", target: assetPath, ok: true, result: r });
          } catch (e) { steps.push({ step: "create", target: assetPath, ok: false, error: e instanceof Error ? e.message : String(e) }); }
        }
        for (const c of (p.components as Array<Record<string, unknown>> ?? [])) {
          await run("add_component", String(c.componentClass ?? ""), "add_component", { path: assetPath, componentClass: c.componentClass, componentName: c.componentName ?? c.componentClass, parentComponent: c.parentComponent, childActorClass: c.childActorClass });
        }
        for (const v of (p.variables as Array<Record<string, unknown>> ?? [])) {
          await run("add_variable", String(v.name ?? ""), "add_variable", { path: assetPath, name: v.name, type: v.varType ?? v.type });
        }
        for (const f of (p.functions as Array<Record<string, unknown>> ?? [])) {
          await run("create_function", String(f.functionName ?? ""), "create_function", { path: assetPath, functionName: f.functionName });
        }
        if ((p.compile ?? true) !== false) {
          await run("compile", assetPath, "compile_blueprint", { path: assetPath });
        }
        const failed = steps.filter(s => !s.ok);
        return { assetPath, created, stepCount: steps.length, failedCount: failed.length, ok: failed.length === 0, steps };
      },
    },
    cleanup_graph: bp("mutate", "Remove orphan/corrupted nodes (no class, blank title+no pins, missing target UFunction). Params: assetPath, graphName? (default: every graph) (#285)", "cleanup_graph", (p) => ({ assetPath: p.assetPath, graphName: p.graphName })),
    connect_pins_batch: bp("mutate", "Apply many pin connections in one call (single compile + save). Params: assetPath, graphName?, connections[]: [{sourceNode, sourcePin, targetNode, targetPin}] (#267)", "connect_pins_batch", (p) => ({ assetPath: p.assetPath, graphName: p.graphName, connections: p.connections })),
    set_node_position: bp("mutate", "Move a graph node to (posX, posY). Params: assetPath, graphName?, nodeId, posX, posY (#277)", "set_node_position", (p) => ({ assetPath: p.assetPath, graphName: p.graphName, nodeId: p.nodeId, posX: p.posX, posY: p.posY })),
    auto_layout: bp("mutate", "Topological layered layout for a graph. Eliminates the (0,0) stack from programmatic add_node. This has no inverse: it rewrites every node's position and set_node_position moves one node per call. It answers that by returning previousPositions, every node's coordinates from before the layout ran, which you replay through set_node_position to undo it. That capture is skipped above previousPositionsLimit nodes (default 200) so a large EventGraph does not return an unbounded array; capturePreviousPositions=true forces it on at any size, and the result says through previousPositionsCaptured which of the two happened. Decide BEFORE running it: once the layout has run the old coordinates are gone. Params: assetPath, graphName?, columnGap? (default 360), rowGap? (default 200), previousPositionsLimit? (default 200), capturePreviousPositions? (default false) (#277)", "auto_layout_graph", (p) => ({ assetPath: p.assetPath, graphName: p.graphName, columnGap: p.columnGap, rowGap: p.rowGap, previousPositionsLimit: p.previousPositionsLimit, capturePreviousPositions: p.capturePreviousPositions })),

    list_interfaces: bp("read", "List the interfaces this Blueprint implements AND the ones it inherits from anywhere in its parent chain. The two halves are told apart by source: an inherited entry carries inheritedFrom, naming the ancestor class that declares it, which for a grandparent is not the immediate parent; an entry the Blueprint declares itself has no ancestor to name and carries no inheritedFrom. Where an inherited interface extends another the base is listed as well, since declaring the derived one puts the base in force too. Every function each declares is reported and whether anything actually answers it: implementedAs is 'graph' (a function graph), 'event' (an override event on the event graph, which is what an interface function with no outputs becomes) or 'missing'. add_interface creates the contract; this is the only thing that reports whether the contract is met, and unimplementedCount is the number to watch. removable is false for an inherited interface, which remove_interface refuses. Params: assetPath", "list_blueprint_interfaces", (p) => ({ assetPath: p.assetPath ?? p.blueprintPath })),
    remove_interface: bp("mutate", "Stop implementing an interface. The paired remove for add_interface, which until now had no inverse and therefore emitted no rollback. preserveFunctions=true keeps the implementations as ordinary Blueprint functions and is the non-destructive form; the default false deletes the interface's function graphs with it, and the result says so through rollbackLossy and names what re-adding would restore. Idempotent: an interface that is not implemented reports alreadyRemoved. An INHERITED interface is refused by name, and the refusal names the ancestor that declares it, which for a grandparent is not the immediate parent: reparenting or editing that class is the only way to drop it. Params: assetPath, interfacePath, preserveFunctions? (default false)", "remove_blueprint_interface", (p) => ({ blueprintPath: p.assetPath ?? p.blueprintPath, interfacePath: p.interfacePath, preserveFunctions: p.preserveFunctions })),

    set_function_properties: bp("mutate", "Set the flags and metadata of a Blueprint function or macro: pure, isConst, accessSpecifier, category, tooltip, keywords, compactNodeTitle, callInEditor, threadSafe, deprecated, deprecationMessage. These are NOT UPROPERTYs on the asset - they live on the function graph's entry node as FUNC_ flags and FKismetUserDeclaredFunctionMetadata - so asset(set_property) cannot reach them. Validates everything before writing anything, reports existed plus unchanged when the request is already the current state, and the rollback restores exactly the fields this call changed. A macro accepts the metadata half only; the flag half is refused by name because a macro compiles to no UFunction. Params: assetPath, functionName, pure?, isConst?, accessSpecifier? (public|protected|private), category?, tooltip?, keywords?, compactNodeTitle?, callInEditor?, threadSafe?, deprecated?, deprecationMessage?", "set_function_properties", (p) => ({ assetPath: p.assetPath, functionName: p.functionName, pure: p.pure, isConst: p.isConst, accessSpecifier: p.accessSpecifier, category: p.category, tooltip: p.tooltip, keywords: p.keywords, compactNodeTitle: p.compactNodeTitle, callInEditor: p.callInEditor, threadSafe: p.threadSafe, deprecated: p.deprecated, deprecationMessage: p.deprecationMessage })),

    list_graph_parameters: bp("read", "Read the parameter signature of a function, macro, event-dispatcher signature or custom event: inputs and outputs with name, type, default value, by-ref and const. The read half of add_function_parameter and edit_graph_parameters. The reported type is the same string the write half accepts (int[], set<Name>, map<Name,int>, object:/Script/Engine.Actor), so a read can be echoed straight back as a call; typeRoundTrips is false for the few pin categories that vocabulary cannot spell. Name exactly one target. Params: assetPath, functionName? OR eventName?, graphName? (narrows an eventName search to one graph)", "list_graph_parameters", (p) => ({ assetPath: p.assetPath, functionName: p.functionName, eventName: p.eventName, graphName: p.graphName })),
    edit_graph_parameters: bp("mutate", "Full parameter CRUD over one mechanism, for every node that owns user-defined pins: a function, a macro, an event-dispatcher signature or a custom event. op=add appends one (creating the function's return node on the first output), remove deletes it, rename rewrites it after probing for a collision so a clash refuses instead of half-renaming, set_type retypes it, set_default writes its default as export text, reorder takes the COMPLETE order and validates every entry before a single pin moves. This is what closes add_function_parameter's documented missing remove. isOutput selects the return side; a custom event and a dispatcher signature are input-only and say so. Params: assetPath, op (add|remove|rename|set_type|set_default|reorder), functionName? OR eventName?, graphName?, isOutput?, parameterName?, parameterType?, newName?, defaultValue?, order?", "edit_graph_parameters", (p) => ({ assetPath: p.assetPath, op: p.op, functionName: p.functionName, eventName: p.eventName, graphName: p.graphName, isOutput: p.isOutput, parameterName: p.parameterName, parameterType: p.parameterType, newName: p.newName, defaultValue: p.defaultValue, order: p.order })),

    rename_variable: bp("mutate", "Rename a member variable, rewriting every get and set node in this Blueprint's graphs, the RepNotify function name and the SCS entry for a component variable. delete_variable plus add_variable loses all of them. Reports referencesBefore, referencesUpdated and referencesStillOnOldName, so the fixup is counted rather than asserted. Refuses a name already taken by another variable on this Blueprint or by a property on the parent class, naming what is taken. Self-inverse rollback. Other Blueprints bind this member by its variable GUID, which the rename preserves; asset(get_asset_referencers) plus compile_all confirms them. Params: assetPath, oldName, newName", "rename_blueprint_variable", (p) => ({ assetPath: p.assetPath, oldName: p.oldName, newName: p.newName })),
    get_variable_metadata: bp("read", "Read every metadata key on a member or local variable (ClampMin, UIMin, EditCondition, Bitmask, BitmaskEnum, MakeEditWidget, MultiLine, and so on). list_variables reports the declaration and set_variable_properties covers category, tooltip and the edit flags; this is the arbitrary-key half, which is not a UPROPERTY and has no other reader. Pass functionName for a local variable. Params: assetPath, name, functionName?", "get_blueprint_variable_metadata", (p) => ({ assetPath: p.assetPath, name: p.name, functionName: p.functionName })),
    set_variable_metadata: bp("mutate", "Write metadata keys on a member or local variable. metadata is an object of key/value strings; a JSON null value removes that key. Unreal stores every metadata value as text, so ClampMin is '0' and EditCondition is 'bEnabled'. Validates the whole object and proves the variable exists in the named scope before writing anything, because the engine setter silently does nothing for a name it cannot find. Idempotent, and the rollback restores each key's previous value or removes it again if it did not exist. Pass functionName for a local variable. Params: assetPath, name, metadata, functionName?", "set_blueprint_variable_metadata", (p) => ({ assetPath: p.assetPath, name: p.name, metadata: p.metadata, functionName: p.functionName })),
    edit_local_variable: bp("mutate", "Complete the local-variable CRUD that add_local_variable and list_local_variables leave half-built. op=rename rewrites the get and set nodes inside the function (a remove-then-add pair would delete them), remove drops the declaration, set_type retypes it, set_default writes its default as export text. remove is idempotent and reports alreadyRemoved. A Blueprint that has never compiled has no function signature to address a local variable through, and that is reported by name rather than failing silently. Params: assetPath, functionName, name, op (rename|remove|set_type|set_default), newName?, varType?, defaultValue?", "edit_local_variable", (p) => ({ assetPath: p.assetPath, functionName: p.functionName, name: p.name, op: p.op, newName: p.newName, varType: p.varType ?? p.type, defaultValue: p.defaultValue })),

    list_event_dispatchers: bp("read", "List this Blueprint's event dispatchers with their parameter signatures. A dispatcher is a multicast-delegate member variable PLUS a separate signature graph, and hasSignatureGraph=false is exactly the state that produces a missing SignatureFunction error at compile time, so it is reported rather than left to be discovered. Params: assetPath", "list_event_dispatchers", (p) => ({ assetPath: p.assetPath ?? p.blueprintPath })),
    remove_event_dispatcher: bp("mutate", "Remove an event dispatcher: BOTH the member variable and its signature graph. delete_variable removes only the variable and leaves an orphan graph the compiler still walks, which is why add_event_dispatcher's rollback pointed at delete_variable and was lossy. Captures the parameter signature first so the inverse re-declares the same one. Idempotent; a variable that is not a dispatcher is refused by name with its actual type. Bind, Unbind and Call nodes go with the variable and are not restored, and the result says so. Params: assetPath, name", "remove_event_dispatcher", (p) => ({ blueprintPath: p.assetPath ?? p.blueprintPath, name: p.name })),

    add_custom_event: bp("mutate", "Add a custom event with a TYPED signature in one call. add_node(nodeClass='CustomEvent') can set the name and nothing else, and has no natural key, so calling it twice silently produces two events; this is idempotent on the event name. parameters is [{name, type}] and becomes the event's output pins. netMode (none|multicast|server|client) with reliable sets the replication flags, and callInEditor exposes the button in the details panel. Every parameter type is validated before the node is created. Params: assetPath, eventName, graphName? (default EventGraph), parameters?, netMode? (none|multicast|server|client), reliable? (default true), callInEditor?, posX?, posY?", "add_custom_event", (p) => ({ assetPath: p.assetPath, eventName: p.eventName, graphName: p.graphName, parameters: p.parameters, netMode: p.netMode, reliable: p.reliable, callInEditor: p.callInEditor, posX: p.posX, posY: p.posY })),

    create_macro: bp("mutate", "Create a Blueprint macro graph with its input and output signature. Macros could be listed by list_functions and read by read_graph but never authored: create_function makes a function, and there was no macro path at all. inputs and outputs are [{name, type}] and land on the entry and exit tunnel nodes; every type is validated before the graph exists. Idempotent on the macro name, and a clash with an existing function or dispatcher graph is refused because graph names share one namespace. Params: assetPath, macroName, inputs?, outputs?, onConflict? (skip|error)", "create_macro", (p) => ({ assetPath: p.assetPath, macroName: p.macroName, inputs: p.inputs, outputs: p.outputs, onConflict: p.onConflict })),
    delete_graph: bp("mutate", "Delete any graph in a Blueprint, addressed the way list_graphs names one. This is the call for a collapsed subgraph that outlived its composite node: delete_function only walks FunctionGraphs and delete_macro only walks MacroGraphs, so both answer alreadyDeleted for an orphan that list_graphs plainly still reports, and leftover variable gets inside it go on blocking delete_variable. While the owning node still exists, delete_node is the right call instead - it takes the bound graph with it - and this refuses rather than leaving the node behind, unless you pass force. Deleting an event graph is refused for the same reason. Idempotent, and reports what it removed: kind, whether it was orphaned, and how many nodes went with it. Params: assetPath, graphName OR graphSelector (needed when two graphs share a name), force? (#1010)", "delete_graph", (p) => ({ path: p.assetPath, graphName: p.graphName, graphSelector: p.graphSelector, force: p.force })),
    delete_macro: bp("mutate", "Delete a macro graph. Idempotent (alreadyDeleted). Reports orphanedInstances, the number of macro instance nodes elsewhere in the Blueprint that referenced it and are now broken - blueprint(cleanup_graph) removes those. The rollback records the macro's input and output signature so re-creating restores the contract; the BODY is not restored and the result says so. Params: assetPath, macroName", "delete_macro", (p) => ({ assetPath: p.assetPath, macroName: p.macroName })),

    read_enum: bp("read", "Read a UserDefinedEnum's whole definition: description, the bitflags switch, and every enumerator with its index, authored short name, editable display name, numeric value and tooltip. asset(list_enum_values) reports the first four columns; this adds the tooltips, the bitflags state and the description, which nothing else could read. Works on native UEnums too, reporting isUserDefined=false. Returns objectPath, because EnumDescription is an ordinary UPROPERTY and belongs to asset(set_property) rather than to a setter here. Params: assetPath", "read_user_defined_enum", (p) => ({ assetPath: p.assetPath })),
    reorder_enum_values: bp("mutate", "Reorder a UserDefinedEnum's enumerators. Enumerator order is authored data with no property behind it, so nothing else could change it. order is the COMPLETE list by display name, authored name or index; a partial list, an unknown entry or a repeat is refused before anything moves, naming the valid values. Idempotent: an order that already holds reports unchanged. The rollback replays the previous order by authored name, which survives further reordering. Params: assetPath, order", "reorder_enum_values", (p) => ({ assetPath: p.assetPath, order: p.order })),
    set_enum_metadata: bp("mutate", "Set a UserDefinedEnum's bitflags switch and its per-enumerator tooltips. The bitflags state is a class metadata key and a tooltip is package metadata keyed by enumerator index, so neither is reachable by a property write. entries is [{name or index, tooltip}] and every entry is resolved before the first write, so a bad entry at position nine leaves the first eight untouched. Idempotent, with a rollback carrying the previous bitflags state and the previous tooltip text keyed by authored name. The enum's own description is a UPROPERTY: use asset(set_property) with propertyName='EnumDescription'. Params: assetPath, bitflags?, entries?", "set_enum_metadata", (p) => ({ assetPath: p.assetPath, bitflags: p.bitflags, entries: p.entries })),

    read_struct: bp("read", "Read a UserDefinedStruct's whole definition: compile status, validity including the recursion check, the struct tooltip, and per field the display name, GUID, type, default value, tooltip, editableOnInstance, saveGame, multiLineText, widget3D and metadata. asset(list_struct_fields) reports name, GUID and a display label; everything else here had no reader. Two fields earn their place on their own. type is a round-trippable spec (int[], set<Name>, map<Name,int>, struct:/Script/CoreUObject.Vector) that can be handed back to a write. propertyName is the generated FProperty name (<name>_<n>_<guid>), which is what a DataTable row and any exported default actually carry, and it is a different thing from the display name; nameMatchesProperty reports whether the two still agree, so after a rename you can see whether the storage key still carries the old spelling. That divergence is the visible cost of a GUID-preserving rename, which is what lets existing pins and rows survive one at all. Params: assetPath", "read_user_defined_struct", (p) => ({ assetPath: p.assetPath })),
    set_struct_field_default: bp("mutate", "Set a UserDefinedStruct member's default value. A member is an FStructVariableDescription inside the struct's editor data, not a UPROPERTY on the asset, so asset(set_property) cannot reach it; the engine call also parses the text against the member's real property and recompiles the struct so every dependent default is repaired, which a raw write would skip. defaultValue is Unreal export text ('5', 'true', '(X=1.000000,Y=2.000000,Z=0.000000)'); an empty string clears it. Resolve the field by fieldName (display or internal name) or fieldGuid. Idempotent, with a rollback carrying the previous value. Params: assetPath, defaultValue, fieldName? OR fieldGuid?", "set_struct_field_default", (p) => ({ assetPath: p.assetPath, defaultValue: p.defaultValue, fieldName: p.fieldName, fieldGuid: p.fieldGuid })),
    reorder_struct_fields: bp("mutate", "Reorder a UserDefinedStruct's members. Member order decides the details-panel layout and the DataTable column order and is authored data with no property behind it. order is the COMPLETE list by display name, internal name or GUID; a partial list, an unknown entry or a repeat is refused before anything moves. Idempotent. A move the engine refuses mid-sequence is reported with complete=false and the count that landed, never as a plain success, and the rollback restores the original order by GUID. Params: assetPath, order", "reorder_struct_fields", (p) => ({ assetPath: p.assetPath, order: p.order })),
    edit_struct_metadata: bp("mutate", "Set a UserDefinedStruct's tooltip and its per-member tooltip, editableOnInstance, saveGame, multiLineText, widget3D and arbitrary metadata, in one batched call. All of these live in the struct's editor data rather than as UPROPERTYs, and each has an engine setter that recompiles the struct. fields is [{fieldName or fieldGuid, tooltip?, editableOnInstance?, saveGame?, multiLineText?, widget3D?, metadata?}]. Every member is resolved and every type-gated switch is checked (multiLineText needs a text-like member, widget3D a Vector or Transform) BEFORE the first write, so a refusal on entry nine leaves entries one through eight untouched. Idempotent; the rollback restores every value by GUID, and states the one thing it cannot: a metadata key that did not exist before is restored to an empty string rather than removed. Params: assetPath, tooltip?, fields?", "edit_struct_metadata", (p) => ({ assetPath: p.assetPath, tooltip: p.tooltip, fields: p.fields })),
    ...epicActions,
  },
  undefined,
  {
    ...epicSchema,
    assetPath: z.string().optional().describe("Blueprint asset path. Read/graph actions also accept a World/umap path (e.g. /Game/Maps/SomeLevel), resolved to that map's level script Blueprint (#942)"),
    // Declared so the transport cannot strip them before `create` folds them
    // into the canonical assetPath (#798).
    path: z.string().optional().describe("Legacy alias for assetPath. Use assetPath (#798)"),
    packagePath: z.string().optional().describe("create: destination folder, used with name. assetPath is the canonical alternative (#798)"),
    graphName: z.string().optional(), functionName: z.string().optional(),
    name: z.string().optional(), varType: z.string().optional().describe("Variable type for add_variable/add_local_variable"),
    // `type` is the name callers reach for first; without it the value was
    // dropped on the floor and the handler silently produced a Float (#745).
    type: z.string().optional().describe("add_variable: alias for varType"),
    onConflict: z.string().optional().describe("add_variable: skip (default) or error when the variable already exists"),
    parentClass: z.string().optional(),
    components: z.array(z.record(z.unknown())).optional().describe("author: [{componentClass, componentName?, parentComponent?, childActorClass?}] (#607)"),
    variables: z.array(z.record(z.unknown())).optional().describe("author: [{name, varType}] (#607)"),
    functions: z.array(z.record(z.unknown())).optional().describe("author: [{functionName}] (#607)"),
    compile: z.boolean().optional().describe("author: compile after authoring (default true) (#607)"),
    category: z.string().optional(), tooltip: z.string().optional(),
    exposeOnSpawn: z.boolean().optional().describe("Toggle ExposeOnSpawn flag on a variable"),
    instanceEditable: z.boolean().optional().describe("set_variable_properties: true = EditAnywhere (per-instance), false = not instance-editable"),
    otherPath: z.string().optional().describe("diff: the compare-against Blueprint (B)"),
    // Forwarded so the handler's explanatory "not wired yet" error still fires.
    // Dropping them turned an explicit rejection into a silent two-asset diff.
    fromRevision: z.string().optional().describe("diff: reserved for revision diffing (not implemented; passing it is an explicit error)"),
    toRevision: z.string().optional().describe("diff: reserved for revision diffing (not implemented; passing it is an explicit error)"),
    editFlag: z.string().optional().describe("set_variable_properties: EditAnywhere|EditDefaultsOnly|EditInstanceOnly|none - the exact value list_variables reports (#744)"),
    private: z.boolean().optional().describe("set_variable_properties: the Blueprint editor's Private checkbox, independent of editFlag"),
    location: z.record(z.unknown()).optional().describe("run_construction_script: {x,y,z} spawn location for the temp actor"),
    oldName: z.string().optional(), newName: z.string().optional(),
    nodeClass: z.string().optional(), nodeParams: z.record(z.unknown()).optional(),
    nodeName: z.string().optional(), propertyName: z.string().optional(),
    value: z.unknown().optional(),
    sourceNode: z.string().optional(), sourcePin: z.string().optional(),
    targetNode: z.string().optional(), targetPin: z.string().optional(),
    sourceNodeId: z.string().optional().describe("connect_pins: source node GUID, as get_connections and find_nodes report it. Unambiguous where a title is not (#996)"),
    targetNodeId: z.string().optional().describe("connect_pins: target node GUID, as get_connections and find_nodes report it (#996)"),
    breakExistingSource: z.boolean().optional().describe("connect_pins: break all existing links on the source pin before connecting"),
    breakExistingTarget: z.boolean().optional().describe("connect_pins: break all existing links on the target pin before connecting"),
    componentClass: z.string().optional(), componentName: z.string().optional(),
    materialPaths: z.array(z.string()).optional().describe("Material asset paths for set_component_override_materials (#442)"),
    timelineName: z.string().optional().describe("Timeline name for add_timeline_track (#457)"),
    trackName: z.string().optional().describe("Track name within the timeline (#457)"),
    // Deliberately a string, not z.enum. The MCP SDK validates arguments BEFORE
    // the tool callback runs, so a strict enum makes a typo fail at the transport
    // with a schema error, and the handler's own message, which names every valid
    // value, never reaches the caller. The handler rejects an unknown track type
    // by listing all four.
    trackType: z.string().optional().describe("add_timeline_track type: float (default) | vector | color | event (#457)"),
    keyframes: z.array(z.record(z.unknown())).optional().describe("add_timeline_track: [{time, value}] - value is number for float/event, {x,y,z} for vector, {r,g,b,a} for color (#457)"),
    halfHeight: z.number().optional().describe("set_capsule_size: capsule half height (unscaled)"),
    radius: z.number().optional().describe("set_capsule_size: capsule radius (unscaled)"),
    parentComponent: z.string().optional().describe("Parent SCS component for add_component hierarchy (#115)"),
    childActorClass: z.string().optional().describe("ChildActorClass for an added ChildActorComponent - Blueprint path (with/without _C) or C++ class (#526)"),
    newParent: z.string().optional().describe("New parent component name for reparent_component"),
    channel: z.string().optional().describe("For get_component_collision: narrow the answer to one collision channel. Accepts the configured name ('Camera', 'Weapon'), the C++ enumerator ('ECC_Camera'), or the container index."),
    includeAllChannels: z.boolean().optional().describe("For get_component_collision: include the unused GameTraceChannel slots as well as the engine channels and the project's own. Default false."),
    bCanEverTick: z.boolean().optional(),
    bStartWithTickEnabled: z.boolean().optional(),
    TickInterval: z.number().optional(),
    parameterName: z.string().optional(), parameterType: z.string().optional(),
    isOutput: z.boolean().optional(),
    // String rather than z.enum for the reason recorded on trackType, and with
    // an extra one here: the value is purely advisory. GetOverrideFunctionClass
    // resolves interface and parent overrides uniformly, so the handler echoes
    // this back and never branches on it. A strict enum spent a transport-level
    // schema error on a field that changes nothing.
    source: z.string().optional().describe("override_function: advisory hint for where the overridable function comes from: auto (default) | interface | parent. Echoed back; the override is resolved the same way either way (#688)"),
    preferFunction: z.boolean().optional().describe("override_function: force the function-graph form even when the function could be placed as an override event (#688)"),
    query: z.string().optional(),
    includeFunctions: z.boolean().optional(),
    includeInherited: z.boolean().optional().describe("list_functions: also list overridable parent/interface functions this Blueprint has not implemented (#809)"),
    includeValues: z.boolean().optional().describe("list_variables: also resolve each variable's default off the generated-class CDO, and report whether the package holds unsaved changes (#902)"),
    blueprintPath: z.string().optional(), interfacePath: z.string().optional(),
    entryPoint: z.string().optional().describe("Event/function name to start exec-flow trace"),
    reverse: z.boolean().optional().describe("get_dependencies: true → referencers of this asset"),
    includeComponentProperties: z.boolean().optional().describe("read: dump UPROPERTY name/type/value per component template (#353/#370)"),
    sourcePath: z.string().optional(), destinationPath: z.string().optional(),
    nodeIds: z.array(z.string()).optional().describe("Node guids/names to export (omit = whole graph)"),
    t3d: z.string().optional().describe("T3D blob from export_nodes_t3d (or copied from the BP graph editor)"),
    className: z.string().optional().describe("C++ class name or path for set_cdo_property / get_cdo_properties, or the declaring class to narrow search_call_sites to (#945)"),
    functionNames: z.array(z.string()).optional().describe("search_call_sites: function names to find call sites for, max 50 per request (#945)"),
    directory: z.string().optional().describe("search_call_sites: content path to search under, recursive, default /Game (#945)"),
    includeNestedGraphs: z.boolean().optional().describe("search_call_sites / find_nodes: also walk collapsed/nested graphs, default true (#945/#1015)"),
    graphSelector: z.string().optional().describe("delete_graph / get_connections: the exact selector list_graphs reports, which separates two graphs sharing a name (#1010/#996)"),
    kind: z.enum(["exec", "data", "all"]).optional().describe("get_connections: which edges to report (default all) (#996)"),
    force: z.boolean().optional().describe("delete_graph: remove a graph that is still owned by a live node, or an event graph. Both are refused without it (#1010)"),
    titles: z.array(z.string()).optional().describe("find_nodes: case-insensitive substrings matched against each node title (#998)"),
    nodeClasses: z.array(z.string()).optional().describe("find_nodes: exact node class names, e.g. K2Node_VariableGet, K2Node_VariableSet (#1015)"),
    variableName: z.string().optional().describe("find_nodes: the member a node reads or writes; matches VariableGet and VariableSet whether or not the property still resolves (#1015)"),
    variableAccess: z.enum(["get", "set", "any"]).optional().describe("find_nodes: narrow variableName to reads, writes, or both (default any) (#1015)"),
    authoredOnly: z.boolean().optional().describe("find_nodes: leave out transient and generated compiler graphs, default true (#998)"),
    includeLevelScripts: z.boolean().optional().describe("search_call_sites: also sweep the level script Blueprint of every map under the directory, which costs a full map load each, default false (#945)"),
    includeNeighbours: z.boolean().optional().describe("search_call_sites: include each hit's immediate execution and data neighbours (#945)"),
    narrowByRegistry: z.boolean().optional().describe("search_call_sites: use Asset Registry dependencies to rule out Blueprints before loading them, default true (#945)"),
    maxBlueprints: z.number().int().positive().optional().describe("search_call_sites: cap on Blueprints loaded, default 2000 (#945)"),
    propertyNames: z.array(z.string()).optional().describe("Property names to read for get_cdo_properties (omit = all)"),
    posX: z.number().optional().describe("Re-center pasted nodes around this X (with posY)"),
    posY: z.number().optional().describe("Re-center pasted nodes around this Y (with posX)"),
    offset: z.number().int().nonnegative().optional().describe("Row offset for read_graph, and the older non-resumable form of search_call_sites paging"),
    // cursor + limit, declared once. Every paged action in this category reads
    // them, and an undeclared key is stripped before the handler sees it.
    ...PAGINATION_SCHEMA,
    includePins: z.boolean().optional().describe("Include pins in read_graph results (default true)"),
    includeGraphNodes: z.boolean().optional().describe("search_node_types: include UEdGraphNode classes alongside function-library entries (default true) (#808)"),
    includeDefaults: z.boolean().optional().describe("Include pin default values in read_graph results (default true)"),
    includeComments: z.boolean().optional().describe("Include node comments in read_graph results (default true)"),
    dumpToFile: z.boolean().optional().describe("Write read_graph JSON to a file instead of returning nodes inline; without offset/limit this dumps the full graph, otherwise it dumps the requested slice"),
    outputPath: z.string().optional().describe("Absolute or Saved-relative JSON path for read_graph dumps; default path includes the asset, graph, and a path hash"),
    titleFilter: z.string().optional().describe("read_graph/read_graph_summary: case-insensitive substring match on node title (#560)"),
    classFilter: z.string().optional().describe("read_graph/read_graph_summary: case-insensitive substring match on node class name (#560)"),
    parameters: z.array(z.object({
      name: z.string(),
      type: z.string().optional(),
    })).optional().describe("add_event_dispatcher: typed signature parameters [{name, type}]. type is bool/int/float/string/name/text/vector/rotator/transform/object:/Script/Module.Class/struct:/Script/Module.Struct"),
    assetPaths: z.array(z.string()).optional().describe("Asset paths for compile_all"),
    save: z.boolean().optional().describe("compile_all: persist on success (default true)"),
    nodeId: z.string().optional().describe("Node guid or name: set_node_position, delete_node, set_node_property (#996)"),
    columnGap: z.number().optional().describe("auto_layout: horizontal spacing between columns (default 360)"),
    rowGap: z.number().optional().describe("auto_layout: vertical spacing between rows (default 200)"),
    previousPositionsLimit: z.number().optional().describe("auto_layout: capture each node's pre-layout coordinates into previousPositions only when the graph has at most this many nodes (default 200). previousPositions is the only way to undo a layout, so raise this for a large graph you may want to put back."),
    capturePreviousPositions: z.boolean().optional().describe("auto_layout: capture previousPositions regardless of previousPositionsLimit (default false). Pass true before laying out a large graph you may want to restore; the pre-layout coordinates cannot be recovered afterwards."),
    connections: z.array(z.object({
      sourceNode: z.string(), sourcePin: z.string(),
      targetNode: z.string(), targetPin: z.string(),
    })).optional().describe("connect_pins_batch: per-connection records"),

    // V9 Blueprint depth.
    preserveFunctions: z.boolean().optional().describe("remove_interface: keep the interface's implementations as ordinary Blueprint functions instead of deleting them with the interface. Default false."),
    pure: z.boolean().optional().describe("set_function_properties: BlueprintPure - the function produces no side effects and its node loses the exec pins."),
    isConst: z.boolean().optional().describe("set_function_properties: const - the function only reads state."),
    // String rather than z.enum for the reason recorded on trackType.
    accessSpecifier: z.string().optional().describe("set_function_properties: who may call the function: public | protected | private."),
    keywords: z.string().optional().describe("set_function_properties: extra palette search keywords for the function's node."),
    compactNodeTitle: z.string().optional().describe("set_function_properties: render the node in compact form under this title."),
    callInEditor: z.boolean().optional().describe("set_function_properties / add_custom_event: expose a button in the details panel that runs it on a selected instance."),
    threadSafe: z.boolean().optional().describe("set_function_properties: declare the function safe to call off the game thread."),
    deprecated: z.boolean().optional().describe("set_function_properties: mark the function deprecated so its call sites warn."),
    deprecationMessage: z.string().optional().describe("set_function_properties: the text shown at a deprecated function's call sites."),
    eventName: z.string().optional().describe("Custom event name for add_custom_event, list_graph_parameters and edit_graph_parameters."),
    op: z.string().optional().describe("edit_graph_parameters op: add | remove | rename | set_type | set_default | reorder. edit_local_variable op: rename | remove | set_type | set_default"),
    defaultValue: z.string().optional().describe("Default value as Unreal export text; an empty string clears it. Used by edit_graph_parameters, edit_local_variable and set_struct_field_default."),
    metadata: z.record(z.unknown()).optional().describe("set_variable_metadata: {key: 'value'} pairs; a null value removes that key. Unreal stores every metadata value as text."),
    // String rather than z.enum for the reason recorded on trackType.
    netMode: z.string().optional().describe("add_custom_event: replication mode for the event: none (default) | multicast | server | client."),
    reliable: z.boolean().optional().describe("add_custom_event: send the replicated event reliably. Default true; ignored when netMode is none."),
    macroName: z.string().optional().describe("Macro graph name for create_macro / delete_macro"),
    inputs: z.array(z.object({ name: z.string(), type: z.string().optional() })).optional().describe("create_macro: input parameters [{name, type}]"),
    outputs: z.array(z.object({ name: z.string(), type: z.string().optional() })).optional().describe("create_macro: output parameters [{name, type}]"),

    // V14 user-type authoring.
    order: z.array(z.unknown()).optional().describe("The COMPLETE desired order, never a partial list. reorder_enum_values takes display names, authored names or indices; reorder_struct_fields takes display names, internal names or GUIDs; edit_graph_parameters with op=reorder takes parameter names."),
    bitflags: z.boolean().optional().describe("set_enum_metadata: mark the enum as a bitflags type, which is what lets a Bitmask variable use it."),
    entries: z.array(z.record(z.unknown())).optional().describe("set_enum_metadata: [{name or index, tooltip}] per-enumerator tooltips"),
    fieldName: z.string().optional().describe("set_struct_field_default: resolve a UserDefinedStruct member by its display or internal name"),
    fieldGuid: z.string().optional().describe("set_struct_field_default: resolve a UserDefinedStruct member by its GUID, which is stable across renames"),
    fields: z.array(z.record(z.unknown())).optional().describe("edit_struct_metadata: [{fieldName or fieldGuid, tooltip?, editableOnInstance?, saveGame?, multiLineText?, widget3D?, metadata?}]"),
  },
);
